name: Update Device Whitelist from Excel

on:
  workflow_dispatch: # 允许手动触发
  push:
    paths:
      - 'data/八位序列号收集（收集结果）.xlsx' # 当Excel文件变化时自动触发
    branches: [ main ]

jobs:
  update-whitelist:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl
        
    - name: Run script to update whitelist
      run: python scripts/update_whitelist.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add whitelist.txt
        git diff --staged --quiet || git commit -m "Update whitelist from Excel - $(date)"
        git push
